services:
  bot:
    image: bot_image
    build:
      context: ./bot
    env_file: .env
    volumes:
      - pg_logs:/var/log/
    restart: no
    depends_on:
      - postgres_primary

  postgres_primary:
    image: db_image
    build:
      context: ./db
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_logs:/var/log/
      - pg_data:/var/lib/postgresql
    restart: no

  postgres_replica:
    image: db_repl_image
    build:
      context: ./db_repl
    env_file: .env
    ports:
      - 5433:5432
    restart: no
    depends_on:
      - postgres_primary
volumes:
  pg_data:
  pg_logs:
